# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 10, 54, 54, 397000, tzinfo=utc)),
        ),
    ]
